---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-default
  namespace: keptn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-helm-service
  namespace: keptn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-lighthouse-service
  namespace: keptn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-api-service
  namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-read-keptndomain
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
    resourceNames:
      - "keptn-domain"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-create-update-configmaps
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-get-update-keptn-ingress
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - ingress
    verbs:
      - get
      - update
    resourceNames:
      - "keptn-ingress"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-get-create-delete-bridge-vs-dstrule
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - virtualservice
      - destinationrule
    verbs:
      - get
      - create
      - delete
    resourceNames:
      - "bridge"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-get-api-vs
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - virtualservice
    verbs:
      - get
    resourceNames:
      - "api"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-lighthouse-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-create-update-configmaps
subjects:
  - kind: ServiceAccount
    name: keptn-lighthouse-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-get-update-keptn-ingress
subjects:
  - kind: ServiceAccount
    name: keptn-api-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-get-create-delete-bridge-vs-dstrule
subjects:
  - kind: ServiceAccount
    name: keptn-api-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-get-api-vs
subjects:
  - kind: ServiceAccount
    name: keptn-api-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-keptndomain
subjects:
  - kind: ServiceAccount
    name: keptn-api-service
    namespace: keptn