---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-default
  namespace: keptn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-helm-service
  namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-read-keptndomain
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
    resourceNames:
      - "keptn-domain"


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-helm-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-keptndomain
subjects:
  - kind: ServiceAccount
    name: keptn-helm-service
    namespace: keptn