---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-default
  namespace: keptn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-helm-service
  namespace: keptn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-lighthouse-service
  namespace: keptn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-shipyard-service
  namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-read-keptndomain
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
    resourceNames:
      - "keptn-domain"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-create-update-configmaps
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-get-delete-update-ingress
  namespace: ingress-nginx
rules:
  - apiGroups:
      - ""
    resources:
      - ingress
      - virtualservice
      - destinationrule
    verbs:
      - get
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-get-delete-update-vs-dstrule
  namespace: keptn-ingress
rules:
  - apiGroups:
      - ""
    resources:
      - ingress
      - virtualservice
      - destinationrule
    verbs:
      - get
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-get-namespaces
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-keptndomain
subjects:
  - kind: ServiceAccount
    name: keptn-helm-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-helm-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-keptndomain
subjects:
  - kind: ServiceAccount
    name: keptn-helm-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-lighthouse-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-create-update-configmaps
subjects:
  - kind: ServiceAccount
    name: keptn-lighthouse-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-get-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-get-namespaces
subjects:
  - kind: ServiceAccount
    name: keptn-helm-service
    namespace: keptn
  - kind: ServiceAccount
    name: keptn-shipyard-service
    namespace: keptn
